main:
    # Conference Reviewers:

    #     - title: IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR) 2021-2023
    #       link: http://cvpr2023.thecvf.com/

    Journal Reviewers:
        - title: IEEE Robotics and Automation Letters
          link: https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=7083369
        - title: IEEE Transactions on Systems, Man, and Cybernetics
          link: https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6221021
        - title: Journal of Field Robotics
          link: https://onlinelibrary.wiley.com/journal/15564967
        - title: IEEE Transactions on Automation Science and Engineering
          link: https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=8856
        - title: Machine Intelligence Research
          link: https://link.springer.com/journal/11633
